# Utiliser l'image officielle NGINX
FROM nginx:latest

# Copier les fichiers frontend (HTML/CSS/JS) vers le répertoire NGINX par défaut
COPY ./ /usr/share/nginx/html

# Expose le port 80 pour servir le frontend
EXPOSE 80
